import "./globals.css";
import type { Metadata } from "next";
import Theme from "./core/Theme";
import { Vazirmatn } from "next/font/google";
import ClientNavbar from "./components/ClientNavbar";
import Footer from "./components/Footer";

const vazirmatn = Vazirmatn({ subsets: ["latin"], weight: "400" });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa">
      <body className={vazirmatn.className}>
        <Theme>
          <ClientNavbar />
          <main>{children}</main>
          <Footer />
        </Theme>
      </body>
    </html>
  );
}
