import "./globals.css";
import type { Metadata } from "next";
import localfont from "next/font/local";

const dana = localfont({
  src: "../public/fonts/dana regular.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={dana.className}>{children}</body>
    </html>
  );
}
